requirejs.config({
    baseUrl:"../js/com",
    paths:{
        jquery:"../lib/jquery/jquery-1.11.3",
        app:"../app"
    }
});
requirejs(["jquery","carousel","app/index","waterfall","goTop"],function($,Carousel,index,Waterfall,GoTop){
    Carousel.init($("#banner"));
    Waterfall.init($(".waterfall"));
    GoTop.init($("#content"));
});